{{- if (empty .Values.existingConfigMap) -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gosqueal.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gosqueal.labels" . | nindent 4 }}
data:
  gosqueal.conf: |
  {{- range $key, $val := .Values.config }}
  {{ $key }}: |
    {{- (tpl $val $) | nindent 4 }}
  {{- end }}
{{- end -}}
